Exercício-2
Desenvolva um programa usando a estrutura “para” que mostre na tela a seguinte contagem: 0 5 10 15 20 25 30 35 40 Acabou!

algoritmo "exercicio-2"
// Autor : Rodrigo Vasconcellos / Professor Guanabara
// Data : 27/09/2022
// Seção de Declarações 

var
   c : inteiro
   
inicio
// Seção de Comandos 

      c <- 0
      para c de 0 ate 40 passo 5 faca
           escreva (c)
      fimpara
      escreva (" acabou!!!!")

fimalgoritmo